spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://d3-cf.com:5432/fision?timezone=UTF-8
    username: fision
    password: fision_admin
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      address: redis://43.136.92.103:6379
      database: 3
      password: Leuan_3rd

