server:
  port: 5555
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
  servlet:
    encoding:
      enabled: true
      charset: UTF-8 # 必须设置 UTF-8，避免 WebFlux 流式返回（AI 场景）会乱码问题
      force: true

spring:
  profiles:
    active: dev
  application:
    name: lepton
  data:
    redis:
      repositories:
        enabled: false
  jackson:
    # 设置 java.util.Date, Calendar 序列化、反序列化的格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: GMT+8
    # 设置对象或被@JsonInclude注解的属性的序列化方式。NON_NULL 表示不为空的属性才会序列化,具体属性可看JsonInclude.Include
    # default-property-inclusion: NON_NULL
    serialization:
      # 禁止将 java.util.Date, Calendar 序列化为数字(时间戳)
      WRITE_DATES_AS_TIMESTAMPS: false
      # 序列化时，对象为 null，是否抛异常
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      # 反序列化时，json 中包含 pojo 不存在属性时，是否抛异常
      FAIL_ON_UNKNOWN_PROPERTIES: false
    data:
      redis:
        repositories:
          enabled: false
  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA
        tenant_identifier_resolver: com.leuan.lepton.framework.common.dal.HibernateTenantResolver
        enable_lazy_load_no_trans: true


--- #################### 接口文档配置 ####################
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档logging:
logging:
  file:
    path: logs

--- #################### 系统配置 ####################
lepton:
  ignore-login-url:
    - /v3/api-docs
    - /auth/login
  ignore-tenant-url:
    - /user/userInfo # 用户可能没有任何租户, 所以不校验租户信息, 在代码中会根据用户是否有租户信息来判断是否需要校验租户信息
    - /tenant/save # 租户保存时不需要校验租户信息
    - /sysPackage/save # 系统套餐保存时需要更新租户信息,所以不需要校验租户信息
  auth:
    token-expire-days: 3