create table customer
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) default CURRENT_TIMESTAMP     not null,
    tenant_id  bigint       default 0                     not null,
    updated_at timestamp(6) default CURRENT_TIMESTAMP     not null,
    name       varchar(255) default ''::character varying not null,
    phone      varchar(255),
    wx         varchar(255),
    created_by bigint
        constraint fkfiw3r4d2twx41tk8tgii23bkp
            references sys_user,
    updated_by bigint
        constraint fkeddix91gc4ir8cqr4ic7po2qm
            references sys_user
);

comment on table customer is '客资';

comment on column customer.created_at is '创建时间';

comment on column customer.tenant_id is '租户ID';

comment on column customer.updated_at is '更新时间';

comment on column customer.name is '姓名';

comment on column customer.phone is '手机号';

comment on column customer.wx is '微信号';

comment on column customer.created_by is '创建人';

comment on column customer.updated_by is '更新人';

alter table customer
    owner to lepton;

