create table sys_user
(
    id       bigint generated by default as identity
        primary key,
    name     varchar(255),
    password varchar(255) not null,
    phone    varchar(255) not null
        constraint ukpulp17fvich5aby4m0kc820h6
            unique,
    avatar   varchar(255)
);

comment on table sys_user is '系统用户';

comment on column sys_user.name is '姓名';

comment on column sys_user.password is '密码';

comment on column sys_user.phone is '手机号';

alter table sys_user
    owner to lepton;

INSERT INTO public.sys_user (id, name, password, phone, avatar) VALUES (1, '杨洋', '$2a$10$97tiDowD7PfPyImFkAOHlu4UC4HH5aA1BHXS2DQJeoiJDBGxEYyHO', '1', null);
INSERT INTO public.sys_user (id, name, password, phone, avatar) VALUES (2, '测试用户', '123', '17600302202', '');
