create table sys_package
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) default ''::character varying not null
);

comment on table sys_package is '套餐';

comment on column sys_package.name is '套餐名称';

alter table sys_package
    owner to lepton;

INSERT INTO public.sys_package (id, name) VALUES (1, '全部功能');
INSERT INTO public.sys_package (id, name) VALUES (5, '用户管理');
