create table sys_tenant
(
    id             bigint generated by default as identity
        primary key,
    name           varchar(255) default ''::character varying       not null,
    type           varchar(255) default 'ACTIVE'::character varying not null
        constraint sys_tenant_type_check
            check ((type)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])),
    sys_package_id bigint
        constraint fk5v6v4ke2k8s02i5660nmcsqw
            references sys_package,
    code           varchar(255) default ''::character varying       not null,
    logo           varchar(255) default ''::character varying       not null
);

comment on column sys_tenant.name is '租户名称';

comment on column sys_tenant.type is '租户类型';

alter table sys_tenant
    owner to lepton;

INSERT INTO public.sys_tenant (id, name, type, sys_package_id, code, logo) VALUES (1, 'Lepton', 'ACTIVE', 1, '', 'https://api.multiavatar.com/tom.png');
INSERT INTO public.sys_tenant (id, name, type, sys_package_id, code, logo) VALUES (23, 'DD', 'ACTIVE', 5, 'DD', '');
