create table sys_role
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) default CURRENT_TIMESTAMP     not null,
    tenant_id  bigint       default 0                     not null,
    updated_at timestamp(6) default CURRENT_TIMESTAMP     not null,
    builtin    boolean      default false                 not null,
    code       varchar(255) default ''::character varying not null,
    name       varchar(255) default ''::character varying not null,
    created_by bigint
        constraint fk2v9r9le66uw53qj87mu5qu26h
            references sys_user,
    updated_by bigint
        constraint fk6jjdu64bjucxh9r503l66l2ai
            references sys_user
);

comment on table sys_role is '系统角色角色';

comment on column sys_role.created_at is '创建时间';

comment on column sys_role.tenant_id is '租户ID';

comment on column sys_role.updated_at is '更新时间';

comment on column sys_role.builtin is '是否内置';

comment on column sys_role.code is '角色编码';

comment on column sys_role.name is '角色名称';

comment on column sys_role.created_by is '创建人';

comment on column sys_role.updated_by is '更新人';

alter table sys_role
    owner to lepton;

INSERT INTO public.sys_role (id, created_at, tenant_id, updated_at, builtin, code, name, created_by, updated_by) VALUES (1, '2024-07-30 05:21:30.868111', 1, '2024-07-30 05:21:30.868111', false, 'super_admin', '超级管理员', null, null);
INSERT INTO public.sys_role (id, created_at, tenant_id, updated_at, builtin, code, name, created_by, updated_by) VALUES (10, '2024-08-04 20:41:53.024000', 20, '2024-08-04 20:41:53.024000', true, 'admin', '管理员', 1, 1);
INSERT INTO public.sys_role (id, created_at, tenant_id, updated_at, builtin, code, name, created_by, updated_by) VALUES (11, '2024-08-04 20:43:36.203000', 21, '2024-08-04 20:43:36.203000', true, 'admin', '管理员', 1, 1);
INSERT INTO public.sys_role (id, created_at, tenant_id, updated_at, builtin, code, name, created_by, updated_by) VALUES (12, '2024-08-04 23:11:36.044000', 22, '2024-08-04 23:11:36.044000', true, 'admin', '管理员', 1, 1);
INSERT INTO public.sys_role (id, created_at, tenant_id, updated_at, builtin, code, name, created_by, updated_by) VALUES (13, '2024-08-04 23:14:09.915000', 23, '2024-08-04 23:49:19.034000', true, 'admin', '管理员', 1, 1);
INSERT INTO public.sys_role (id, created_at, tenant_id, updated_at, builtin, code, name, created_by, updated_by) VALUES (2, '2024-08-03 14:33:39.289000', 1, '2024-08-04 23:59:00.692000', false, 'operation', '运营', 1, 1);
